-- ==========================================================================
-- GLOBAL TEC — SUPABASE SETUP (safe to run more than once)
-- Dashboard → SQL Editor → New query → paste this whole file → Run.
--
-- This replaces the old schema.sql. It drops any existing "products" table
-- first (fixes the "policy already exists" / "invalid input syntax for
-- type uuid" errors — those happened because a table already existed with
-- a uuid id column from an earlier attempt). If you already have real
-- products saved in Supabase that you care about, stop and tell me before
-- running this — it deletes that table's data. If you're just getting
-- set up, it's safe to run.
-- ==========================================================================

-- 1) Clean slate for the products table -----------------------------------
drop table if exists public.products cascade;

create table public.products (
  id            text primary key,        -- e.g. "dell-5420-a1b2" — auto-generated by the admin panel
  name          text not null,
  brand         text not null,
  condition     text not null default 'used' check (condition in ('new', 'used')),
  price         integer not null,
  old_price     integer,                 -- nullable, only set when on sale
  processor     text,
  ram           text,
  storage       text,
  gpu           text,
  screen        text,
  description   text,
  image_url     text,                    -- main product image
  image_gallery jsonb not null default '[]'::jsonb,  -- array of extra image URLs
  in_stock      boolean not null default true,
  created_at    timestamptz not null default now()
);

-- 2) Row Level Security ----------------------------------------------------
alter table public.products enable row level security;

create policy "Public can read products"
  on public.products
  for select
  using (true);

create policy "Signed-in users can insert products"
  on public.products
  for insert
  to authenticated
  with check (true);

create policy "Signed-in users can update products"
  on public.products
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Signed-in users can delete products"
  on public.products
  for delete
  to authenticated
  using (true);

-- 3) Storage bucket for product photos --------------------------------------
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- 4) Storage policies (drop-then-create so this is safe to re-run) ---------
drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
  on storage.objects for select
  using ( bucket_id = 'product-images' );

drop policy if exists "Signed-in users can upload product images" on storage.objects;
create policy "Signed-in users can upload product images"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'product-images' );

drop policy if exists "Signed-in users can update product images" on storage.objects;
create policy "Signed-in users can update product images"
  on storage.objects for update
  to authenticated
  using ( bucket_id = 'product-images' );

drop policy if exists "Signed-in users can delete product images" on storage.objects;
create policy "Signed-in users can delete product images"
  on storage.objects for delete
  to authenticated
  using ( bucket_id = 'product-images' );
