-- ==========================================================================
-- GLOBAL TEC — SEED DATA
-- Run this ONCE after schema.sql, to load your current 13 real laptops into
-- Supabase. Dashboard → SQL Editor → New query → paste this file → Run.
-- After this, add/edit everything from admin.html instead.
-- ==========================================================================

insert into public.products
  (id, name, brand, condition, price, old_price, processor, ram, storage, gpu, screen, description, image_url, image_gallery, in_stock)
values
  ('p01', 'Dell Latitude 3420 (Touch)', 'Dell', 'used', 10700, 11500, 'Intel Core i5 (11th Gen)', 'Not specified by seller — ask us', 'Not specified by seller — ask us', 'Intel integrated graphics', '14" FHD Touchscreen', 'Latitude 3420 with an 11th-Gen Core i5 for solid everyday speed and efficiency. Slim, durable build that''s easy to carry, with a responsive 14" FHD touchscreen. Full modern connectivity including USB Type-C and HDMI.', 'images/Dell/dell-3420/photo-1.png', '["images/Dell/dell-3420/photo-1.png", "images/Dell/dell-3420/photo-2.png"]'::jsonb, true),
  ('p02', 'Dell Latitude 5400', 'Dell', 'used', 9500, 10200, 'Intel Core i5-8365U (8th Gen)', '8GB DDR4 (expandable up to 32GB)', '256GB M.2 NVMe SSD', 'Intel UHD Graphics 620 (integrated)', '14" FHD (1920x1080) Anti-Glare', 'A dependable 8th-Gen business laptop with anti-glare FHD display. Ports include USB Type-C (DisplayPort/charging), 3x USB 3.1, HDMI, LAN (RJ-45), and a MicroSD card reader.', 'images/Dell/dell-5400/photo-1.png', '["images/Dell/dell-5400/photo-1.png", "images/Dell/dell-5400/photo-2.png", "images/Dell/dell-5400/photo-3.png"]'::jsonb, true),
  ('p03', 'Dell Latitude 5420 (Touch)', 'Dell', 'used', 11950, 12700, 'Intel Core i5-1135G7 (11th Gen)', '8GB DDR4 (expandable up to 64GB)', '256GB M.2 NVMe SSD', 'Intel Iris Xe Graphics', '14" FHD (1920x1080) Anti-Glare, Touch', '11th-Gen Latitude with a touch display and Intel Iris Xe graphics. Ports include 2x Thunderbolt 4 (Type-C), USB 3.2, HDMI 2.0, LAN (RJ-45), and MicroSD. Around 1.37kg with ExpressCharge fast-charging support.', 'images/Dell/dell-5420/photo-1.png', '["images/Dell/dell-5420/photo-1.png", "images/Dell/dell-5420/photo-2.png", "images/Dell/dell-5420/photo-3.png"]'::jsonb, true),
  ('p04', 'Dell Latitude 5521', 'Dell', 'used', 21000, 22500, 'Intel Core i7-11850H (11th Gen H-series, 8C/16T)', '16GB or 32GB DDR4 (expandable up to 64GB)', '256GB / 512GB / 1TB M.2 NVMe PCIe SSD', 'Intel UHD Graphics / NVIDIA GeForce MX450 2GB GDDR6 (on select units)', '15.6" FHD (1920x1080) IPS Anti-Glare', 'A powerful H-series Latitude for demanding workloads, with configurations available up to 1TB storage and dedicated MX450 graphics on select units. Ports include 2x Thunderbolt 4 (Type-C), USB 3.2, HDMI 2.0, LAN (RJ-45), and MicroSD.', 'images/Dell/dell-5521/photo-1.png', '["images/Dell/dell-5521/photo-1.png", "images/Dell/dell-5521/photo-2.png", "images/Dell/dell-5521/photo-3.png"]'::jsonb, true),
  ('p05', 'Dell Latitude 7320 (Touch)', 'Dell', 'used', 15200, 16900, 'Intel Core i5-1135G7 or i5-1145G7 vPro (11th Gen)', '16GB LPDDR4x (soldered — not upgradeable)', '256GB NVMe M.2 SSD (upgradeable to larger capacity)', 'Intel Iris Xe Graphics', '13.3" FHD (1920x1080), Touch', 'A premium, ultra-light business Ultrabook built for people who travel with their laptop daily. Metal chassis keeps it durable without adding weight.', 'images/Dell/dell-7320/photo-1.png', '["images/Dell/dell-7320/photo-1.png", "images/Dell/dell-7320/photo-2.png"]'::jsonb, true),
  ('p06', 'Dell Latitude 5590 (Core i7)', 'Dell', 'used', 12900, 13900, 'Intel Core i7-7600U (7th Gen, dual-core, up to 3.90GHz)', '8GB DDR4 (expandable up to 32GB, 2 slots)', '256GB M.2 NVMe SSD', 'AMD Radeon 540 / Vega Graphics (2GB dedicated)', '15.6" HD or Full HD (depending on unit)', 'Latitude-series build quality with dedicated AMD graphics — a good pick for everyday work plus light creative tasks. Ports: 3x USB 3.1, USB Type-C, VGA + HDMI, LAN (RJ-45), SD card reader, combo audio jack.', 'images/Dell/dell-5590/photo-1.png', '["images/Dell/dell-5590/photo-1.png", "images/Dell/dell-5590/photo-2.png", "images/Dell/dell-5590/photo-3.png"]'::jsonb, true),
  ('p07', 'Dell Latitude 7490 (Core i7)', 'Dell', 'used', 8888, 9500, 'Intel Core i7 (8th Gen)', '8GB DDR4 (16GB configurations available on request)', '256GB SSD (512GB available on request)', 'Intel UHD Graphics 620 (integrated)', '14" FHD, slim design', 'A light, capable daily-driver for multitasking and everyday office work — a solid pick for freelancers, employees, and students. Supports Type-C, HDMI, USB 3.1, Wi-Fi, and Bluetooth.', 'images/Dell/dell-7490/photo-1.png', '["images/Dell/dell-7490/photo-1.png", "images/Dell/dell-7490/photo-2.png", "images/Dell/dell-7490/photo-3.png"]'::jsonb, true),
  ('p08', 'HP ProBook 650 G3 (Core i7)', 'HP', 'used', 9500, 10200, 'Intel Core i7 (7th Gen, HQ-series)', '8GB DDR4', '256GB SSD', 'Intel integrated graphics (HQ-class processor)', '15.6", wide viewing area', 'Built for heavier workloads and engineering/programming use with an HQ-class processor. Includes a dedicated numpad for comfortable data entry. Ports: USB Type-C, DisplayPort, VGA, USB 3.0, LAN, card reader.', 'images/HP/hp-650-g3/photo-1.png', '["images/HP/hp-650-g3/photo-1.png", "images/HP/hp-650-g3/photo-2.png"]'::jsonb, true),
  ('p09', 'HP EliteBook x360 830 G6', 'HP', 'used', 13900, 14600, 'Intel Core i7-8565U (8th Gen)', '8GB or 16GB DDR4 SODIMM (expandable up to 32GB, 2 slots)', '256GB M.2 NVMe SSD', 'Intel UHD Graphics (integrated)', '13.3" FHD (1920x1080) Touch, 360° convertible, Active Pen support', 'A convertible 2-in-1 business laptop with a full-aluminum chassis and Bang & Olufsen audio. Ports: 2x Thunderbolt 3 (Type-C), 2x USB 3.1, HDMI 1.4b, card reader, Smart Card, combo audio. About 1.35kg.', 'images/HP/hp-830-g6-x360/photo-1.png', '["images/HP/hp-830-g6-x360/photo-1.png", "images/HP/hp-830-g6-x360/photo-2.png"]'::jsonb, true),
  ('p10', 'HP EliteBook 845 G8 (Ryzen 5)', 'HP', 'used', 14300, 14800, 'AMD Ryzen 5 5650U (6-core)', '16GB DDR4 (expandable up to 64GB)', '256GB SSD NVMe, High-Speed', 'AMD Radeon Graphics (integrated)', '14" FHD (1920x1080) IPS Anti-Glare', 'Full-aluminum chassis at around 1.37kg, built for everyday business use and multitasking. Security features include a fingerprint reader and a physical camera privacy shutter. Ports: 2x USB-C (charging & data), 2x USB-A 3.1, HDMI 2.0.', 'images/HP/hp-845-g8/photo-1.png', '["images/HP/hp-845-g8/photo-1.png", "images/HP/hp-845-g8/photo-2.png"]'::jsonb, true),
  ('p11', 'HP EliteBook 845 G9', 'HP', 'used', 19300, 21000, 'AMD Ryzen 5 PRO 6650U', '16GB DDR5', '512GB NVMe SSD', 'AMD Radeon 660M', '14" WUXGA (1920x1200), 250 nits', 'A newer-generation EliteBook with DDR5 memory and a sharper WUXGA display — a strong step up in both speed and screen quality over the G8.', 'images/HP/hp-845-g9/photo-1.png', '["images/HP/hp-845-g9/photo-1.png", "images/HP/hp-845-g9/photo-2.png"]'::jsonb, true),
  ('p12', 'HP ZBook Fury G7', 'HP', 'used', 28500, 29500, 'Intel Core i7-10750H / i7-10850H (vPro) / i9-10885H / Xeon E-2286M (ECC-capable)', 'DDR4, 4 SODIMM slots, up to 128GB (ECC supported with Xeon configurations)', 'M.2 NVMe SSD, up to 4 slots — supports RAID 0/1, up to 8–10TB total', 'NVIDIA Quadro series — configured with NVIDIA Quadro T1200 (4GB GDDR6)', '15.6" mobile workstation display', 'A mobile workstation built for demanding engineering and CAD software, with certified NVIDIA Quadro graphics and support for ECC memory on Xeon configurations. Exact CPU/RAM/storage vary by unit — ask us for the configuration currently in stock.', 'images/HP/hp-zbook-fury-g7/photo-1.png', '["images/HP/hp-zbook-fury-g7/photo-1.png", "images/HP/hp-zbook-fury-g7/photo-2.png", "images/HP/hp-zbook-fury-g7/photo-3.png"]'::jsonb, true),
  ('p13', 'HP ZBook Power G8', 'HP', 'used', 31000, 33000, 'Intel Core i7-11800H (11th Gen H-series, 8C/16T)', 'DDR4 3200MHz, 2 SODIMM slots, from 16GB up to 64GB', 'M.2 NVMe PCIe SSD (Gen 4 supported), from 512GB up to 2TB (up to 4TB with a second drive, RAID 0/1 supported)', 'Intel UHD Graphics (integrated) / NVIDIA T1200 4GB GDDR6 (dedicated, for CAD & rendering)', '15.6" anti-glare — configurations include FHD IPS 250nits, FHD Low Power 400nits (100% sRGB), and 4K UHD IPS 400nits (100% sRGB); touch-screen versions available', 'A mobile workstation built for CAD and rendering work, with dedicated NVIDIA T1200 graphics and a choice of display panels up to 4K. Exact configuration depends on the unit in stock — ask us for current specs.', 'images/HP/hp-zbook-power-g8/photo-1.png', '["images/HP/hp-zbook-power-g8/photo-1.png", "images/HP/hp-zbook-power-g8/photo-2.png", "images/HP/hp-zbook-power-g8/photo-3.png"]'::jsonb, true);
